# === maze2d ===
env_name: "maze2d-medium-v1"
dim_mult: [1, 4, 2]
w_cg: 0.0
horizon: 256
sg_weight: 100.
proj_range: [0.3, 0.4]
n_manifold_samples: 10
use_proj_mask: 0
proj_mask_threshold: 0.5
action_dim_weight: 0.0

# === multi2d ===
# env_name: "maze2d-medium-v1"
# dim_mult: [1, 4, 2]
# w_cg: 0.0
# horizon: 256
# sg_weight: 100.
# proj_range: [0.4, 0.9]
# n_manifold_samples: 10
# use_proj_mask: 0
# proj_mask_threshold: 0.5
# action_dim_weight: 1.0