defaults:
  - _self_
  - task: antmaze-medium-play-v2

pipeline_name: lomaphd_d4rl_antmaze
mode: train
seed: 0
device: cuda:0

# Environment
noreaching_penalty: -100
discount: 0.99

# Diffuser
solver: ddpm
model_dim: 32
diffusion_steps: 20
sampling_steps: 20
predict_noise: False
next_obs_loss_weight: 10. 
ema_rate: 0.9999

# Training
diffusion_gradient_steps: 1000000
classifier_gradient_steps: 1000000
invdyn_gradient_steps: 1000000  
batch_size: 64
log_interval: 1000
save_interval: 100000

# Faiss
faiss_similarity: "cosine" 
faiss_nlist: 1000 

# Inference
diffusion_ckpt: latest
classifier_ckpt: latest 
invdyn_ckpt: latest
num_envs: 50
num_episodes: 1
num_candidates: 64
temperature: 0.5
use_ema: True
tau: 0.99

# hydra
hydra:
  job:
    chdir: false

