defaults:
  - _self_
  - task: maze2d-large-v1

pipeline_name: lomapdiffuser_d4rl_maze2d
mode: train
seed: 0
device: cuda:0
multi_task: False

# Environment
discount: 0.997

# Diffuser
solver: ddpm
model_dim: 32
diffusion_steps: 256
sampling_steps: 256
predict_noise: False
action_loss_weight: 1.
ema_rate: 0.9999

# Training
diffusion_gradient_steps: 1000000
classifier_gradient_steps: 1000000
batch_size: 64
log_interval: 1000
save_interval: 100000

# Faiss
faiss_similarity: "cosine"
faiss_nlist: 1000

# Inference
ckpt: latest
num_envs: 50
num_episodes: 20
num_candidates: 1
temperature: 1.0
use_ema: True
tau: 0.99

# hydra
hydra:
  job:
    chdir: false

